---
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: end-of-file-fixer
      - id: check-added-large-files
        args:
          - --maxkb=4096
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-json
      - id: check-toml

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
      - id: shellcheck
        args:
          - --shell=bash
      - id: shfmt

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.15.1
    hooks:
      - id: stylua-system

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
        stages:
          - commit-msg
