assume_yes = true

only = [
  "system",
  "brew_formula",
  "brew_cask",
  "krew",
  "mas",
  "custom_commands",
  "rustup",
]

run_in_tmux = false
set_title = false
display_time = true
cleanup = true

[pre_commands]
"Generate Brewfile" = "${HOME}/bin/ref-gen-brewfile"
"Install Brewfile managed packages" = "brew bundle install --no-upgrade --file=${HOME}/.config/brew/Brewfile"

[commands]
"Brewfile Consistency Check" = "brew bundle cleanup --force --file=${HOME}/.config/brew/Brewfile"
"Helm Charts Repos Update" = "helm repo update"
